title: Kn0rki.de
description: "A Jekyll Blog Theme"
author:
  name: "kn0rki"
  email: "someone@somewebsite.somedomain"
  url: "https://kn0rki.de"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Kn0rki"
year : "2020"
